-- =============================================================================
-- Açılış oy tablosu  —  ÜRETİLMİŞ DOSYA, ELLE DÜZENLEMEYİN
--
--   node scripts/generate-seed-sql.mjs
--
-- Yüzdeler ve dağıtım algoritması src/data/seedShares.ts içinde. Ülke geneli
-- yüzdeleri tam tutturulur; bölgesel eğilim yalnızca illere dağılımı değiştirir.
-- Toplam 365 oy, 193 satır.
--
-- Bu tohum GERÇEK OYLARDAN AYRI tutulur (public.seed_tallies). Migration
-- yeniden çalıştırıldığında önce eski tohum province_tallies'ten düşülür,
-- sonra yenisi eklenir — böylece oyuncuların gerçek oyları hiç bozulmaz ve
-- yüzdeler her seferinde yeniden hedefe oturur.
-- =============================================================================

create table if not exists public.seed_tallies (
  province_id text not null references public.provinces (id) on delete cascade,
  party_id    text not null references public.parties   (id) on delete cascade,
  votes       int  not null check (votes >= 0),
  primary key (province_id, party_id)
);

alter table public.seed_tallies enable row level security;
-- Politika yok: istemci okumaz, yalnızca migration yazar.

-- 1) Önceki tohumu geri al
update public.province_tallies pt
   set votes = greatest(0, pt.votes - st.votes)
  from public.seed_tallies st
 where st.province_id = pt.province_id and st.party_id = pt.party_id;

delete from public.province_tallies where votes = 0;
delete from public.seed_tallies;

-- 2) Yeni tohum
insert into public.seed_tallies (province_id, party_id, votes) values
  ('afyonkarahisar', 'akp', 1),
  ('afyonkarahisar', 'yeni', 1),
  ('afyonkarahisar', 'mhp', 2),
  ('afyonkarahisar', 'iyi', 3),
  ('afyonkarahisar', 'memleket', 1),
  ('afyonkarahisar', 'chp', 1),
  ('afyonkarahisar', 'tip', 1),
  ('afyonkarahisar', 'gelecek', 1),
  ('ankara', 'akp', 10),
  ('ankara', 'yeni', 7),
  ('ankara', 'mhp', 2),
  ('ankara', 'yrp', 1),
  ('ankara', 'anahtar', 1),
  ('ankara', 'sp', 1),
  ('ankara', 'gelecek', 1),
  ('ankara', 'zafer', 1),
  ('artvin', 'akp', 4),
  ('artvin', 'yeni', 2),
  ('artvin', 'iyi', 1),
  ('artvin', 'yrp', 1),
  ('artvin', 'memleket', 1),
  ('artvin', 'deva', 1),
  ('artvin', 'dp', 1),
  ('artvin', 'bbp', 1),
  ('aydin', 'akp', 4),
  ('aydin', 'yeni', 2),
  ('aydin', 'iyi', 2),
  ('aydin', 'memleket', 1),
  ('aydin', 'chp', 2),
  ('balikesir', 'akp', 6),
  ('balikesir', 'yeni', 3),
  ('balikesir', 'mhp', 1),
  ('balikesir', 'iyi', 1),
  ('balikesir', 'yrp', 1),
  ('balikesir', 'chp', 1),
  ('balikesir', 'tip', 1),
  ('balikesir', 'deva', 1),
  ('balikesir', 'zafer', 1),
  ('bolu', 'akp', 5),
  ('bolu', 'yeni', 4),
  ('bolu', 'mhp', 2),
  ('bolu', 'iyi', 1),
  ('bolu', 'yrp', 1),
  ('bolu', 'memleket', 1),
  ('bolu', 'dp', 1),
  ('bursa', 'akp', 6),
  ('bursa', 'yeni', 3),
  ('bursa', 'mhp', 1),
  ('bursa', 'iyi', 1),
  ('bursa', 'yrp', 1),
  ('bursa', 'dem', 1),
  ('bursa', 'anahtar', 1),
  ('bursa', 'chp', 1),
  ('bursa', 'sp', 1),
  ('bursa', 'dp', 1),
  ('corum', 'akp', 7),
  ('corum', 'yeni', 5),
  ('corum', 'mhp', 1),
  ('corum', 'anahtar', 1),
  ('corum', 'bbp', 1),
  ('gaziantep', 'akp', 2),
  ('gaziantep', 'yeni', 2),
  ('gaziantep', 'yrp', 1),
  ('gaziantep', 'dem', 2),
  ('gaziantep', 'memleket', 1),
  ('gaziantep', 'anahtar', 1),
  ('gaziantep', 'tip', 1),
  ('gaziantep', 'sp', 1),
  ('gaziantep', 'deva', 1),
  ('gaziantep', 'gelecek', 1),
  ('gaziantep', 'hudapar', 1),
  ('isparta', 'akp', 2),
  ('isparta', 'yeni', 4),
  ('isparta', 'mhp', 1),
  ('isparta', 'iyi', 1),
  ('isparta', 'memleket', 1),
  ('isparta', 'tip', 1),
  ('isparta', 'sp', 1),
  ('isparta', 'deva', 1),
  ('isparta', 'dp', 1),
  ('mersin', 'akp', 6),
  ('mersin', 'yeni', 2),
  ('mersin', 'mhp', 1),
  ('mersin', 'iyi', 1),
  ('mersin', 'yrp', 1),
  ('mersin', 'anahtar', 1),
  ('mersin', 'chp', 1),
  ('mersin', 'tip', 1),
  ('mersin', 'deva', 1),
  ('mersin', 'gelecek', 1),
  ('istanbul', 'akp', 14),
  ('istanbul', 'yeni', 5),
  ('istanbul', 'mhp', 4),
  ('istanbul', 'iyi', 1),
  ('istanbul', 'yrp', 2),
  ('istanbul', 'dem', 1),
  ('istanbul', 'memleket', 1),
  ('istanbul', 'chp', 1),
  ('istanbul', 'tip', 2),
  ('istanbul', 'sp', 1),
  ('istanbul', 'gelecek', 1),
  ('istanbul', 'dp', 1),
  ('istanbul', 'zafer', 1),
  ('kars', 'akp', 4),
  ('kars', 'yeni', 1),
  ('kars', 'mhp', 1),
  ('kars', 'yrp', 1),
  ('kars', 'dem', 3),
  ('kocaeli', 'akp', 7),
  ('kocaeli', 'yeni', 1),
  ('kocaeli', 'iyi', 2),
  ('kocaeli', 'yrp', 1),
  ('kocaeli', 'memleket', 1),
  ('kocaeli', 'chp', 1),
  ('konya', 'akp', 6),
  ('konya', 'yeni', 2),
  ('konya', 'mhp', 3),
  ('konya', 'anahtar', 1),
  ('konya', 'sp', 1),
  ('konya', 'dp', 1),
  ('konya', 'bbp', 1),
  ('konya', 'zafer', 1),
  ('manisa', 'yeni', 3),
  ('manisa', 'mhp', 1),
  ('manisa', 'iyi', 2),
  ('manisa', 'yrp', 1),
  ('manisa', 'memleket', 1),
  ('manisa', 'anahtar', 1),
  ('manisa', 'tip', 1),
  ('manisa', 'zafer', 1),
  ('rize', 'akp', 4),
  ('rize', 'yeni', 2),
  ('rize', 'mhp', 1),
  ('sakarya', 'akp', 2),
  ('sakarya', 'yeni', 2),
  ('sakarya', 'mhp', 1),
  ('sakarya', 'iyi', 1),
  ('sakarya', 'yrp', 1),
  ('sakarya', 'anahtar', 1),
  ('sakarya', 'chp', 1),
  ('sakarya', 'sp', 1),
  ('sakarya', 'gelecek', 1),
  ('sinop', 'akp', 5),
  ('sinop', 'yeni', 6),
  ('sinop', 'mhp', 1),
  ('sinop', 'iyi', 1),
  ('trabzon', 'akp', 3),
  ('trabzon', 'yeni', 4),
  ('trabzon', 'mhp', 2),
  ('trabzon', 'yrp', 1),
  ('trabzon', 'memleket', 1),
  ('trabzon', 'anahtar', 1),
  ('trabzon', 'deva', 1),
  ('sanliurfa', 'akp', 1),
  ('sanliurfa', 'yeni', 2),
  ('sanliurfa', 'yrp', 1),
  ('sanliurfa', 'dem', 4),
  ('sanliurfa', 'memleket', 1),
  ('sanliurfa', 'anahtar', 1),
  ('sanliurfa', 'tip', 1),
  ('sanliurfa', 'sp', 1),
  ('sanliurfa', 'deva', 1),
  ('sanliurfa', 'gelecek', 1),
  ('sanliurfa', 'hudapar', 1),
  ('usak', 'akp', 2),
  ('usak', 'yeni', 3),
  ('usak', 'iyi', 2),
  ('usak', 'memleket', 1),
  ('usak', 'chp', 2),
  ('usak', 'tip', 1),
  ('zonguldak', 'akp', 2),
  ('zonguldak', 'yeni', 3),
  ('zonguldak', 'mhp', 2),
  ('zonguldak', 'iyi', 1),
  ('zonguldak', 'anahtar', 1),
  ('zonguldak', 'sp', 1),
  ('zonguldak', 'bbp', 1),
  ('bartin', 'akp', 3),
  ('bartin', 'yeni', 5),
  ('bartin', 'mhp', 2),
  ('bartin', 'yrp', 1),
  ('bartin', 'deva', 1),
  ('karabuk', 'akp', 5),
  ('karabuk', 'yeni', 1),
  ('karabuk', 'mhp', 2),
  ('karabuk', 'iyi', 1),
  ('karabuk', 'bbp', 1),
  ('kilis', 'akp', 5),
  ('kilis', 'yeni', 1),
  ('kilis', 'yrp', 1),
  ('kilis', 'dem', 4),
  ('kilis', 'memleket', 1),
  ('kilis', 'hudapar', 1)
on conflict (province_id, party_id) do update set votes = excluded.votes;

-- 3) Tohumu gerçek sayaçların üstüne ekle
insert into public.province_tallies (province_id, party_id, votes)
select province_id, party_id, votes from public.seed_tallies
on conflict (province_id, party_id)
  do update set votes = public.province_tallies.votes + excluded.votes;
